### ISSUE TITLE
неправильно очередность пакетом. противоречит принятым конвенциям

### ISSUE THREAD

**Issue by Roshiajin** [ZubkovVO/mailtest#1]
https://github.com/ZubkovVO/mailtest/blob/a799cb46e7dd94c81e47dbc2b3083c5acf204c10/src/main/java/pf/epam/com/MainMailPage.java#L1

**Comment by ZubkovVO** [comment]
Structure refactored in the following commit
https://github.com/ZubkovVO/mailtest/commit/c553aaca7974f107895a88eed65473b2f424523b
